Sponsor level list
pybay/pybay_old pull request #115
Opened 2017-06-21 03:12 UTC by sesas

Cleaned up PR from: https://github.com/pybay/pybay/pull/113 
PR from JD for speakers_list.html and sponsor_level_list.html templates
"speakers list needs new work per GL work but follows the Variant wireframes. sponsor level list is ok per GL."

2017-06-21 05:24 UTC, sesas commented
@epsy Fixed the conflict

2017-06-21 10:35 UTC, superglu commented
Apparently I don't have push access to this. Due to PR #123, please remove any changes to speaker_list.html to avoid conflicting with that PR.

2017-06-21 22:38 UTC, sesas commented
@superglu I reverted the changes to `speaker_list.html` and the only file remaining is `sponsor_level_list.html`. Would you be able to review this PR and merge?

2017-06-22 03:28 UTC, epsy requested changes
Please rebase

2017-06-22 03:28 UTC, epsy commented on pybay/templates/frontend/sponsor_level_list.html
>            <a class="sl-logo" href="{{ sponsor.external_url }}">
please remove commented code

2017-06-22 03:28 UTC, epsy commented on pybay/templates/frontend/sponsor_level_list.html
>              <p class="sl-link"><a href="{{ sponsor.external_url }}">{{ sponsor.external_url }}</a></p>
same

2018-04-15 08:46 UTC, closed without merging