Add rollbar
pybay/pybay_old pull request #79
Opened 2017-05-24 03:29 UTC by PirosB3

Adds rollbar support

2017-05-24 03:46 UTC, epsy requested changes

2017-05-24 03:46 UTC, epsy commented on pybay/settings.py
> +    "rollbar.contrib.django.middleware.RollbarNotifierMiddleware",
Should this be last? We might want to put it earlier if we want to be notified of errors in the django middlewares

2017-05-24 03:46 UTC, epsy commented on pybay/settings.py
> +import rollbar
Q: Does this import have to be at the bottom?

2017-05-24 03:46 UTC, epsy commented on pybay/settings.py
> +    import rollbar
Q: can we not import this on top?

2017-05-24 03:49 UTC, PirosB3 commented on pybay/settings.py
> +    import rollbar
no because they need to have access to django settings

2017-05-30 19:18 UTC, epsy requested changes

2017-05-30 19:18 UTC, epsy commented on pybay/settings.py
> +if os.environ.get('TRAVIS', False):
you missed a ``not``

2017-05-31 01:44 UTC, PirosB3 commented on pybay/settings.py
> +    "rollbar.contrib.django.middleware.RollbarNotifierMiddleware",
good idea

2017-05-31 02:01 UTC, epsy approved these changes

2017-05-31 02:52 UTC, mzdaniel commented
This rollbar thing look pretty. Thank you Daniel!

Couple of comments:
* Please review the dev environment. I am getting: 
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/data/pybay/pybay/settings.py", line 229, in <module>
    with open('/home/pybay/rollbar.txt') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/pybay/rollbar.txt'
for that conditional.
* Then for merging into prod, lets squash all those commits

2017-06-05 15:20 UTC, PirosB3 commented
@mzdaniel did all changes

2017-06-06 01:42 UTC, merged

2017-06-06 01:48 UTC, mzdaniel commented
Ok. Maybe coincidence but looks like 'branch' attribute is needed on ROLLBAR setting. 
Added that, commits squashed and rebased, and deployed in prod.