Add bootstrap accordion to FAQ page
pybay/pybay_old pull request #98
Opened 2017-06-10 23:49 UTC by superglu

Update faq.html to incorporate css classes for a bootstrap accordion, and update the link from the sponsors page to link directly to a specific spot in it.

2017-06-11 11:44 UTC, epsy requested changes
See in-line comments.
Has @grace-law signed off on the design?

For another review, we should auto-collapse on mobile.

2017-06-11 11:44 UTC, epsy commented on pybay/templates/frontend/faq_box.html
> +                  <a href="{% url 'pybay_faq' %}#sponsors">More FAQs</a>
This include is used on the frontpage and registration pages, so use a template variable for this. See https://docs.djangoproject.com/en/1.11/ref/templates/builtins/#include

2017-06-11 11:44 UTC, epsy commented on pybay/templates/frontend/faq.html
> +                                {% for slug, title, faqs in faq_categories %}
OPT: this is indented too far

2017-06-11 23:13 UTC, grace-law commented
I can look at it after 7p today :)

Thanks everyone for the awesome contribution!

Sent from my iPhone

> On Jun 11, 2017, at 4:44 AM, Yann Kaiser <notifications@github.com> wrote:
> 
> @epsy requested changes on this pull request.
> 
> See in-line comments.
> Has @grace-law signed off on the design?
> 
> For another review, we should auto-collapse on mobile.
> 
> In pybay/templates/frontend/faq_box.html:
> 
> > @@ -23,7 +23,7 @@
>              </div>
>              <div class="row">
>                  <p class="more-link">
> -                  <a href="{% url 'pybay_faq' %}">More FAQs</a>
> +                  <a href="{% url 'pybay_faq' %}#sponsors">More FAQs</a>
> This include is used on the frontpage and registration pages, so use a template variable for this. See https://docs.djangoproject.com/en/1.11/ref/templates/builtins/#include
> 
> In pybay/templates/frontend/faq.html:
> 
> > -                        {% if faq_categories|length > 1 %}
> -                            <h2 class="blue-header"><strong>{{ title }}</strong></h2>
> -                        {% endif %}
> -                        <div class="faq-items">
> -                            {% for faq in faqs %}
> -                                <a name="faq-{{ faq.id }}" style="position:relative;top:-60px">&nbsp;</a> {# The anchor with margin is just to get the page to scroll down a bit and not hide the title. #}
> -                                <div class="faq-item" id="faq-{{ faq.id }}">
> -                                    <h3 class="lead blue-header"><strong>{{ faq.title }}</strong> <a class="glyphicon glyphicon-link" href="#faq-{{ faq.id }}"></a></h3>
> -                                    <p>
> -                                        {{ faq.body | safe }}
> -                                    </p>
> -                                </div>
> -                            {% endfor %}
> -                        </div>
> +                    <div class="panel-group id=accordion">
> +                                {% for slug, title, faqs in faq_categories %}
> OPT: this is indented too far
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
>

2017-06-13 19:14 UTC, PirosB3 commented
Can you make a PR towards master?

2017-06-13 19:16 UTC, PirosB3 commented on pybay/templates/frontend/faq.html
> +                                                            <a name="faq-{{ faq.id }}" style="position:relative;top:-60px">&nbsp;</a> {# The anchor with margin is just to get the page to scroll down
did you test this on mobile?

2017-06-13 19:24 UTC, epsy commented on pybay/templates/frontend/faq.html
> +                                                            <a name="faq-{{ faq.id }}" style="position:relative;top:-60px">&nbsp;</a> {# The anchor with margin is just to get the page to scroll down
This is something Simeon added. If it needs to be changed, this must be done in a separate review.

2017-06-14 02:13 UTC, closed without merging